"""add_field_size_to_file_table

Revision ID: b323a7a804e9
Revises: 7a2f3f138e7d
Create Date: 2023-03-31 20:01:38.690953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b323a7a804e9'
down_revision = '7a2f3f138e7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stored_file', sa.Column('size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stored_file', 'size')
    # ### end Alembic commands ###
